### ISSUE TITLE
Are spaces valid in SWIs ?

### ISSUE THREAD

**Issue by dp111** [hoglet67/PiTubeDirect#144]
In tube-swi.c tube_SWI_NumberFromString are spaces valid ? if not then we should be using ">" instead of ">=".

**Comment by hoglet67** [comment]
This is the behaviour I see on RISCOS 3.1 in Arculator:
![Screenshot from 2021-12-17 12-18-15](https://user-images.githubusercontent.com/1951463/146543750-eb52dfdc-8e9e-45b9-927d-ffcb83d18a10.png)

So it looks like space is treated as a valid terminator, rather than as a valid character.

I'll update the code to use >
