### ISSUE TITLE
Fast 6502 model broken on gpu branch on Pi Zero

### ISSUE THREAD

**Issue by BigEd** [hoglet67/PiTubeDirect#4]
The 6502tubeasm model, the faster 6502 model, does not work on the gpu branch because it relies on a register update to service an interrupt. We have a slower approach which we use on multi-core Pi.

**Comment by hoglet67** [comment]
This is now fixed:
0c204c6b6f35960a226b6bff1616b6b36b19def4

The fix was to adopt the same pattern that the multi core build uses, so the fix is mostly just changing IFDEFs

The effect is a very significant slow down, from CLOCKSP of 225.19MHz (master) to 56.38MHz (gpu), due to the extra polling

See this issue for ideas about regaining this performance:
https://github.com/hoglet67/PiTubeDirect/issues/9
